apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
spec:
  storageClassName: storage-rampup
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /opt/database
    server: 172.31.18.187
    readOnly: false
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: node-name
          operator: In
          values:
          - worker01
