apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-role
rules:
  - apiGroups:
      - ""
      - "extensions"
      - "networking.k8s.io"
    resources:
      - configmaps
      - secrets
      - endpoints
      - ingresses
      - nodes
      - pods
    verbs:
      - list
      - watch
      - get
      - update
  - apiGroups:
      - ""
    resources:
      - services
    verbs:
      - list
      - watch
      - get
      - update
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
  - apiGroups:
      - "extensions"
      - "networking.k8s.io"
    resources:
      - ingresses/status
    verbs:
      - update
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - list
      - watch
      - get
      - update
