apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  labels:
    app: nginx
    type: test
spec:
  selector:
    type: test
  ports:
    - name: nginx-http
      port: 80
      nodePort: 30001
  type: NodePort
