
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-config-map
spec:
  containers:
  - image: busybox
    name: busy-configmap-box
    command:
    - sleep
    - "3600"
    envFrom:
    - configMapRef:
        name: config-map
